# Generated by Django 4.0.6 on 2022-10-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatetexts',
            name='language_code_destiny',
            field=models.CharField(max_length=2),
        ),
    ]
