# Generated by Django 4.2.4 on 2023-10-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_translatetexts_language_code_destiny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatetexts',
            name='language_code_destiny',
            field=models.CharField(choices=[('en', 'english'), ('de', 'deutch'), ('fr', 'francaise'), ('zh-Hans', 'chinese')], max_length=7),
        ),
    ]
