# Generated by Django 4.2.4 on 2023-10-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_alter_translatetexts_language_code_destiny'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_analyze', models.CharField(max_length=255)),
                ('sentiment_result', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='translatetexts',
            name='language_code_destiny',
            field=models.CharField(choices=[('fr', 'francaise'), ('en', 'english'), ('zh-Hans', 'chinese'), ('de', 'deutch')], max_length=7),
        ),
    ]
